name: tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Debug

jobs:
  test:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
    - uses: actions/checkout@v3

    - name: install_shedskin
      run: python setup.py install --user
      
    - name: install_conan
      run: pip install conan==1.59.0
      
    - name: test
      run: cd tests; shedskin test --conan
