name: msys2 tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Debug

jobs:
  test:
    name: Msys2 tests
    runs-on: windows-latest
    env:
      MSYSTEM: UCRT64
    defaults:
      run:
        shell: msys2 {0}

    strategy:
      fail-fast: false

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Setup python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
          cache: 'pip'
        
      - name: Setup msys2
        uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: >-
            mingw-w64-ucrt-x86_64-toolchain
            mingw-w64-ucrt-x86_64-pkgconf
            mingw-w64-ucrt-x86_64-cmake
            mingw-w64-ucrt-x86_64-ninja

      - name: Display Python version
        run: |
          python -c "import sysconfig, platform; print(platform.system(), sysconfig.get_python_version())"
          python -c "import sysconfig; print(sysconfig.get_paths())"
          python -c "import sys; print(sys.executable)"
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
        
      - name: Install shedskin
        run: pip install .

      - name: Test shedskin
        run: |
          cd tests
          shedskin test --conan -c'Python_ROOT_DIR="$pythonLocation"'
